### ISSUE TITLE
Use of a Colorpicker

### ISSUE THREAD

**Issue by svandeneertwegh** [sabueso/ticketator#76]
We could make use of a colorpicker in the project.
As for example on the place "new state" in admin settings.

- Low - Enhancement

**Comment by sabueso** [comment]
Hi @svandeneertwegh 

Sorry about the delay in my answer, I'm a little busy last months.

The project is actually using a colorpicker (django-colorfield) but I see that is broken when the page loads.

My apologies, I'll fix it ASAP!

**Comment by sabueso** [comment]
Hi again @svandeneertwegh 

Now colorpicker is fixed in "devel" branch: the project was using a library from a website that is not online anymore.

You have the commit here https://github.com/sabueso/ticketator/commit/35fb7a765954c36d3d2c3b5e96e8839d417694e9

Please, pull the changes if you're using the devel branch.

Cheers!
